#!/bin/bash

sudo pacman -S --noconfirm git xorg xorg-xinit icewm rofi lxterminal xfce4-clipman-plugin xfce4-screenshooter gpicview redshift lxsession btop lxtask engrampa

git clone https://github.com/bikass/kora.git ~/

git clone https://gitlab.com/tearch-linux/artworks/themes-and-icons/adwaita-dark-amoled.git ~/

mkdir ~/.icewm
mkdir ~/.config
mkdir ~/.icewm/themes
mkdir ~/.config/rofi
mkdir ~/.themes
mkdir ~/.themes/adwaita-dark-amoled
mkdir ~/.icons
mkdir ~/.icons/kora
mkdir ~/.icons/kora-light
mkdir ~/.icons/kora-pgrey
mkdir ~/.icons/kora-light-panel

cp ~/adwaita-dark-amoled/* ~/.themes/adwaita-dark-amoled
cp ~/kora/kora/* ~/.themes/kora
cp ~/kora/kora-light/* ~/.icons/kora-light
cp ~/kora/kora-pgrey/* ~/.icons/kora-pgrey
cp ~/kora/kora-light-panel/* ~/.icons/kora-light-panel
cp icewm/configs/* ~/.icewm
cp xinitrc/xinitrc.txt ~/.xinitrc
cp rofi/config.rasi ~/.config/rofi
tar -xvf icewm/themes/neonoid.tar ~/elytraos/icewm/themes
cp icewm/themes/* ~/.icewm/themes
cp appearance/gtkrc-2.0 ~/.gtkrc-2.0

rm -rf ~/adwaita-dark-amoled
rm -rf ~/kora
